name: 'Gitbook Action Build'
on:
  push:
    branches:
      - main  # trigger branch

jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      # Check out the repo first
      - name: Checkout code
        uses: actions/checkout@v2
      # Run this action to publish gitbook
      - name: Publish
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
